Define Abstract Machine Rules
cannonlang/Specification pull request #2
Opened 2021-07-09 23:41 UTC by chorman0773

These rules replace the previously adopted definitions of "ill-formed", "implementation-defined", "unspecified", and "undefined".

2021-07-09 23:45 UTC, rdrpenguin04 requested changes
`Cannon` is inconsistently capitalized, and the numbered lists have different formatting in the markdown. I haven't read the rest yet, just some obvious typographical inconsistencies.

2021-07-10 00:15 UTC, rdrpenguin04 approved these changes
LGTM

2021-07-10 01:25 UTC, konsumlamm approved these changes

2021-08-29 04:35 UTC, merged

2021-09-21 23:59 UTC, chorman0773 commented
Pursuant to Interpretation made at Core WG Meeting 14, this may have been without sufficient authority. A question of whether to sustain this will be presented at Core WG Meeting 15